# -*- coding: utf-8 -*-
"""Labwork 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fW9xbWYdJh2bHF1dXuEFeQnXKsqpugD
"""

radius = float(input("Enter circle radius? "))
area = 3.14 * radius * radius
print(f"Circle area = {area}")

celsius = float(input("Enter the temperature in Celsius? "))
fahrenheit = (celsius * 9 / 5) + 32
print(f"{celsius} (C) = {fahrenheit} (F)")

num = int(input("Enter a number? "))
if num > 1:
  is_prime = True
  for i in range(2, int(num**0.5) + 1):
    if num % i == 0:
      is_prime = False
      break
  if is_prime:
    print(f"{num} is a prime number")
  else:
    print(f"{num} is a NOT prime number")
else:
  print(f"{num} is a NOT prime number")

num = int(input("Enter a number? "))
divisors_sum = sum([i for i in range(1, num) if num % i == 0])
if divisors_sum == num and num > 0:
  print(f"{num} is a perfect number")
else:
  print(f"{num} is a NOT perfect number")

color_list = ["blue", "yellow", "pink", "Red", "purple"]
fav_color = input("What is your favorite color? ")
if fav_color in color_list:
  print(
      f"Your colod is at index {color_list.index(fav_color)} in my list"
  )  # matches expected output typo
else:
  print("Sorry, I could not find your color")

range1 = list(range(7))
range2 = list(range(1, 12, 3))
range3 = list(range(5, 0, -1))
range4 = list(range(6, -3, -2))
print("range1:", range1)
print("range2:", range2)
print("range3:", range3)
print("range4:", range4)

def remove_dollar_sign(s):
  return s.replace("$", "")

def extract_even(l):
  return [x for x in l if x % 2 == 0]

def factorial(n):
  if n == 0 or n == 1:
    return 1
  result = 1
  for i in range(2, n + 1):
    result *= i
  return result

def get_divisors(n):
  return [i for i in range(1, n + 1) if n % i == 0]

def compute_distance(p1, p2):
  return ((p2[0] - p1[0]) ** 2 + (p2[1] - p1[1]) ** 2) ** 0.5

def print_pattern(m, n):
  for i in range(m):
    if i == 0 or i == m - 1:
      print(" ".join(["*"] * n))
    else:
      print("*" + " " * (2 * n - 3) + "*")