# -*- coding: utf-8 -*-
"""Labwork 1b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjwKEvKVS_VLBp3RLU1R_9hfH1VrCZ7c
"""

def input_num_students():
  return int(input("Enter number of students in a class: "))


def input_student_info():
  student_id = input("Enter student ID: ")
  name = input("Enter student name: ")
  dob = input("Enter student Date of Birth (DoB): ")
  return {"id": student_id, "name": name, "dob": dob}


def input_num_courses():
  return int(input("Enter number of courses: "))


def input_course_info():
  course_id = input("Enter course ID: ")
  name = input("Enter course name: ")
  return {"id": course_id, "name": name}


def input_marks(students, courses):
  print("\nAvailable Courses:")
  list_courses(courses)
  course_id = input("Select a course ID to input marks for: ")

  marks = {}
  for student in students:
    mark = float(input(f"Enter mark for student {student['name']} (ID: {student['id']}): "))
    marks[student["id"]] = mark

  return course_id, marks


def list_courses(courses):
  print("\n--- Course List ---")
  for course in courses:
    print(f"ID: {course['id']}, Name: {course['name']}")


def list_students(students):
  print("\n--- Student List ---")
  for student in students:
    print(f"ID: {student['id']}, Name: {student['name']}, DoB: {student['dob']}")


def show_student_marks(course_id, course_marks, students, courses):
  course_name = next((c['name'] for c in courses if c['id'] == course_id), "Unknown")
  print(f"\n--- Marks for Course: {course_name} (ID: {course_id}) ---")
  for student in students:
    s_id = student['id']
    mark = course_marks.get(s_id, "N/A")
    print(f"Student: {student['name']} (ID: {s_id}) - Mark: {mark}")